POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lb3cyQGNhdC5jYSIsImV4cCI6MTcyNTY0MzE2NCwidXNlcklkIjoyfQ.FydJSeTkTW_WdHLzBOJAQyrTZ2XaJEhcLuAR7Jqbj68

{
  "title": "meows event 2",
  "description": "first test request from http-client plugin",
  "location": "calgary"
}