POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lb3dfMkBjYXQuY2EiLCJleHAiOjE3MjU1ODkzMTUsInVzZXJJZCI6MH0.FsFVlmEcVRBqPnZ6gvjMarXAmbSct3hrdipYWSu1JsQ

{
  "title": "hello from api 1",
  "description": "first test request from http-client plugin",
  "location": "calgary"
}